### ISSUE TITLE
DevOps Engineering

### ISSUE THREAD

**Issue by samubura** [e-scooter-2077/documentation#6]
Section regarding the description of the DevOps techniques applied to the project.

**Comment by ldeluigi** [comment]
**Missing stuff:**

- [x] Unit tests
- [x] Code coverage
- [x] Static Code Analysis
- [x] Badges:
    - [x] FLOSS
    - [x] ci test results
    - [x] coverage
    - [x] code analysis
    - [x] size
    - [x] version
    - [x] ... see shields.io

**Comment by ldeluigi** [comment]
Implement some unit tests + add readme for:
- [x] Admin Api Gateway
- [x] Customer / Manage Customers
- [x] Rent payment mock
- [x] Rent / Manage Rents
- [x] Rent / Manage Scooter Availability
- [x] Scooter Control
- [x] Scooter Monitor
- [x] Scooter Monitor / Manage Reported Properties
- [x] Scooter Monitor / Manage Telemetry Updates
- [x] Scooter Physical Control / Manage Devices

Create ci+tests+"test in ci" + readme + badges for:
- [x] Customer frontend
- [x] Admin frontend
- [x] Customer Mock
- [x] Device Emulator
- [x] Scooter Data Mock

Adjust readme for:
- [x] Rent service

**Comment by ldeluigi** [comment]
## Considerations

- FLOSS badges require too much time to be obtained. We have too many FOSS repos.
- Code coverage require a third part service or a GitHub secretn Gist for each repo. Too much time to setup.
- The previous point means no coverage badge
- Code analysis resulting in the security tab seems to be unsupported by shields.io. This means no CodeQL badge.
- Size badge is useless

**Comment by francescodente** [comment]
The actions mentioned in the DevOps page need to be updated after the adoption of reusable workflows.
